Select * from CovidData;

SELECT SEX,ID,PATIENT_TYPE FROM CovidData;


Q.1
SELECT PREGNANT ,PATIENT_TYPE,COUNT(*) AS TOTAL_PATIENTS FROM CovidData
GROUP BY SEX,PATIENT_TYPE, PREGNANT;

Q.2 

With TotalICUAdmissions AS(
    SELECT COUNT(*) AS Total FROM CovidData
WHERE ICU =1
)

SELECT 
      MEDICAL_UNIT,
	  COUNT(*) AS ICUAdmission,
	  ROUND((COUNT(*) * 100.0)/
(SELECT Total FROM TotalICUAdmissions), 2) AS
Percentage

FROM CovidData
WHERE ICU = 1
GROUP BY MEDICAL_UNIT
ORDER BY ICUAdmission DESC



Q.3

SELECT COUNT(*) AS INTUBEDWITHPNEUMONIA
FROM CovidData
WHERE INTUBED = 1 AND PNEUMONIA =1;

Q.4

SELECT
      ID,
	  AGE,
	  ICU,
	  DEATH
FROM CovidData
WHERE ICU=1 AND DEATH=1 AND AGE>60
ORDER BY AGE DESC;
